"""
LLM models for the PAOP system.

These models provide integration with various LLM providers such as Ollama and Gemini.
"""

from enum import Enum
from typing import Any, Dict, List, Optional, Union, Literal
from pydantic import BaseModel, Field, validator


class LLMProvider(str, Enum):
    """Supported LLM providers."""
    
    OLLAMA = "ollama"
    GEMINI = "gemini"
    ANTHROPIC = "anthropic" 
    OPENAI = "openai"


class LLMModelConfig(BaseModel):
    """Configuration for an LLM model."""
    
    provider: LLMProvider = Field(..., description="LLM provider")
    model_name: str = Field(..., description="Name of the model to use")
    temperature: float = Field(0.7, description="Temperature for generation")
    max_tokens: Optional[int] = Field(None, description="Maximum tokens to generate")
    top_p: Optional[float] = Field(None, description="Top-p sampling parameter")
    top_k: Optional[int] = Field(None, description="Top-k sampling parameter")
    stop_sequences: Optional[List[str]] = Field(None, description="Sequences that stop generation")
    api_key: Optional[str] = Field(None, description="API key (if not using environment variable)")
    api_base: Optional[str] = Field(None, description="API base URL (for Ollama this is the host)")


class LLMPromptTemplate(BaseModel):
    """Template for prompting an LLM."""
    
    template: str = Field(..., description="Prompt template with placeholders")
    input_variables: List[str] = Field(..., description="Variables to be replaced in the template")
    
    def format(self, **kwargs) -> str:
        """Format the template with the provided variables."""
        template = self.template
        for var in self.input_variables:
            if var in kwargs:
                template = template.replace(f"{{{var}}}", str(kwargs[var]))
        return template


class LLMRequestPayload(BaseModel):
    """Payload for an LLM request."""
    
    prompt: str = Field(..., description="Prompt to send to the LLM")
    system_prompt: Optional[str] = Field(None, description="System prompt (for providers that support it)")
    tool_definitions: Optional[List[Dict[str, Any]]] = Field(None, description="Tool definitions for function calling")
    

class LLMResponsePayload(BaseModel):
    """Response from an LLM request."""
    
    text: str = Field(..., description="Generated text from the LLM")
    finish_reason: Optional[str] = Field(None, description="Reason for finishing generation")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="Tool calls generated by the LLM")
    token_usage: Optional[Dict[str, int]] = Field(None, description="Token usage information")


class LLMTaskDefinition(BaseModel):
    """Task definition for interacting with an LLM."""
    
    task_type: Literal["llm_request"] = Field("llm_request", description="Type of task")
    model_config: LLMModelConfig = Field(..., description="LLM model configuration")
    prompt_template: Optional[LLMPromptTemplate] = Field(None, description="Prompt template")
    request_payload: Optional[LLMRequestPayload] = Field(None, description="Request payload")
    use_tools: bool = Field(False, description="Whether to enable tool use for the LLM")
    tool_configs: Optional[List[Dict[str, Any]]] = Field(None, description="Configurations for tools to provide to the LLM")


class OllamaModelInfo(BaseModel):
    """Information about an Ollama model."""
    
    name: str = Field(..., description="Name of the model")
    size: int = Field(..., description="Size of the model in bytes")
    modified_at: str = Field(..., description="Timestamp when the model was last modified")
    details: Optional[Dict[str, Any]] = Field(None, description="Additional model details")


class OllamaModelPullRequest(BaseModel):
    """Request to pull an Ollama model."""
    
    name: str = Field(..., description="Name of the model to pull")
    insecure: Optional[bool] = Field(False, description="Whether to skip TLS verification")
