#!/bin/bash
# run_everything.sh - Comprehensive script to run the entire PAOP system
# This script handles setup, building, testing, and running the system

# Exit on error
set -e

# Set colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Set up logging
LOG_FILE="paop_run_log.txt"
echo "=== PAOP System Run Log ($(date)) ===" > $LOG_FILE

# Display header
echo -e "${BOLD}==================================================${NC}"
echo -e "${BOLD}      Pedantic Agent Orchestration Platform       ${NC}"
echo -e "${BOLD}==================================================${NC}"
echo

# Function to log messages
log_message() {
    local level=$1
    local message=$2
    local color=$NC
    
    case $level in
        "INFO") color=$GREEN ;;
        "WARN") color=$YELLOW ;;
        "ERROR") color=$RED ;;
    esac
    
    echo -e "${color}[$level] $message${NC}"
    echo "[$level] $message" >> $LOG_FILE
}

# Function to check prerequisites
check_prerequisites() {
    log_message "INFO" "Checking prerequisites..."
    
    # Check Python
    if ! command -v python3 &> /dev/null; then
        log_message "ERROR" "Python 3 is required but not installed"
        exit 1
    fi
    
    PYTHON_VERSION=$(python3 --version | cut -d ' ' -f 2)
    log_message "INFO" "Found Python version: $PYTHON_VERSION"
    
    # Check if pip is installed
    if ! command -v pip3 &> /dev/null; then
        log_message "ERROR" "pip3 is required but not installed"
        exit 1
    fi
    
    # Check for Docker (optional)
    if command -v docker &> /dev/null; then
        DOCKER_AVAILABLE=true
        DOCKER_VERSION=$(docker --version | cut -d ' ' -f 3 | tr -d ',')
        log_message "INFO" "Found Docker version: $DOCKER_VERSION"
    else
        DOCKER_AVAILABLE=false
        log_message "WARN" "Docker not found (optional - required for container deployment)"
    fi
    
    log_message "INFO" "Prerequisites check completed"
}

# Function to set up environment
setup_environment() {
    log_message "INFO" "Setting up environment..."
    
    # Set API key environment variable if not already set
    if [[ -z "${PAOP_API_KEY}" ]]; then
        export PAOP_API_KEY="dev-key-DO-NOT-USE-IN-PRODUCTION"
        log_message "INFO" "Set PAOP_API_KEY environment variable for local development"
    fi
    
    # Make scripts executable
    log_message "INFO" "Making scripts executable..."
    chmod +x scripts/*.sh
    chmod +x src/main.py
    chmod +x src/supervisor.py
    
    # Create Python virtual environment if it doesn't exist
    if [ ! -d ".venv" ]; then
        log_message "INFO" "Creating Python virtual environment..."
        python3 -m venv .venv
    else
        log_message "INFO" "Python virtual environment already exists"
    fi
    
    # Activate virtual environment
    log_message "INFO" "Activating virtual environment..."
    source .venv/bin/activate
    
    # Install dependencies
    log_message "INFO" "Installing dependencies..."
    pip install -r requirements.txt >> $LOG_FILE 2>&1
    
    # Install the package in development mode
    log_message "INFO" "Installing the package in development mode..."
    pip install -e . >> $LOG_FILE 2>&1
    
    # Check for MCP config
    if [ ! -f "config/mcp_config.yml" ]; then
        log_message "WARN" "MCP configuration not found at config/mcp_config.yml"
        
        # Create the mcp_config.yml file with MCP disabled
        mkdir -p config
        cat > config/mcp_config.yml << EOF
# MCP Configuration 
# Generated by run_everything.sh

# Basic configuration options
mcp:
  enabled: false  # Disabled for local development
  executable_path: /usr/local/bin/desktopcommander-mcp
  config_path: $(pwd)/config/mcp
  timeout_seconds: 30
  retry_count: 3
  retry_delay_seconds: 2
  
  # Environment variables to set when calling MCP
  environment_variables:
    MCP_LOG_LEVEL: INFO
    MCP_CONFIG_DIR: $(pwd)/config/mcp
EOF
        log_message "INFO" "Created config/mcp_config.yml with MCP disabled"
    fi
    
    # Check for supervisor config
    if [ ! -f "config/supervisor.yml" ]; then
        log_message "WARN" "Supervisor configuration not found at config/supervisor.yml"
        
        # Create the supervisor.yml file
        mkdir -p config
        cat > config/supervisor.yml << EOF
# Supervisor Configuration
# Generated by run_everything.sh

# Global configuration
mcp_config_path: $(pwd)/config/mcp_config.yml

# Agent configurations
agents:
  - agent_id: orchestrator-1
    name: PAOP Orchestrator
    description: Main orchestrator agent for the PAOP
    role: orchestrator
    is_orchestrator: true
    config_path: $(pwd)/config/agent-orchestrator.yml
  
  - agent_id: worker-1
    name: Worker Agent 1
    description: Standard worker agent for processing tasks
    role: worker
    config_path: $(pwd)/config/agent-worker.yml
  
  - agent_id: worker-2
    name: Worker Agent 2
    description: Secondary worker agent for processing tasks
    role: worker
    config_path: $(pwd)/config/agent-worker.yml
EOF
        log_message "INFO" "Created config/supervisor.yml"
    fi
    
    # Check for orchestrator config
    if [ ! -f "config/agent-orchestrator.yml" ]; then
        log_message "WARN" "Orchestrator configuration not found at config/agent-orchestrator.yml"
        
        # Create the agent-orchestrator.yml file
        mkdir -p config
        cat > config/agent-orchestrator.yml << EOF
# Orchestrator Agent Configuration
# Generated by run_everything.sh

agent:
  id: orchestrator-1
  name: PAOP Orchestrator
  description: Main orchestrator agent for the PAOP
  role: orchestrator
  is_orchestrator: true
  
logging:
  level: INFO
  format: "%(asctime)s [%(levelname)s] %(name)s - %(message)s"
EOF
        log_message "INFO" "Created config/agent-orchestrator.yml"
    fi
    
    # Check for worker config
    if [ ! -f "config/agent-worker.yml" ]; then
        log_message "WARN" "Worker configuration not found at config/agent-worker.yml"
        
        # Create the agent-worker.yml file
        mkdir -p config
        cat > config/agent-worker.yml << EOF
# Worker Agent Configuration
# Generated by run_everything.sh

agent:
  id: worker-1
  name: Worker Agent
  description: Standard worker agent for processing tasks
  role: worker
  is_orchestrator: false
  
logging:
  level: INFO
  format: "%(asctime)s [%(levelname)s] %(name)s - %(message)s"
EOF
        log_message "INFO" "Created config/agent-worker.yml"
    fi
    
    # Check for API config
    if [ ! -f "config/api_config.json" ]; then
        log_message "WARN" "API configuration not found at config/api_config.json"
        
        # Create the api_config.json file
        mkdir -p config
        cat > config/api_config.json << EOF
{
    "api": {
        "host": "0.0.0.0",
        "port": 8000,
        "debug": true,
        "reload": true,
        "log_level": "info",
        "api_keys": ["dev-key-DO-NOT-USE-IN-PRODUCTION"]
    },
    "orchestrator": {
        "id": "orchestrator-1",
        "host": "localhost",
        "port": 50051
    },
    "security": {
        "cors_origins": ["*"],
        "trusted_hosts": ["localhost", "127.0.0.1"],
        "rate_limit": {
            "enabled": true,
            "limit": 100,
            "timespan": 60
        }
    }
}
EOF
        log_message "INFO" "Created config/api_config.json"
    fi
    
    log_message "INFO" "Environment setup completed"
}

# Function to run tests
run_tests() {
    log_message "INFO" "Running tests..."
    
    # Run linting if flake8 is installed
    if command -v flake8 &> /dev/null; then
        log_message "INFO" "Running linting..."
        flake8 src tests >> $LOG_FILE 2>&1 || log_message "WARN" "Linting found issues (see log for details)"
    else
        log_message "WARN" "flake8 not installed, skipping linting"
    fi
    
    # Run unit tests
    log_message "INFO" "Running unit tests..."
    if pytest tests/unit/ -v >> $LOG_FILE 2>&1; then
        log_message "INFO" "Unit tests completed successfully"
    else
        log_message "WARN" "Some unit tests failed (see log for details)"
        log_message "INFO" "Continuing despite test failures"
    fi
}

# Function to run the local system
run_local_system() {
    log_message "INFO" "Starting the PAOP system locally..."
    
    # Set API key environment variable if not already set
    if [[ -z "${PAOP_API_KEY}" ]]; then
        export PAOP_API_KEY="dev-key-DO-NOT-USE-IN-PRODUCTION"
        log_message "INFO" "Set PAOP_API_KEY environment variable for local development"
    fi
    
    # Create a new terminal window/tab to run the API
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        osascript -e 'tell app "Terminal" to do script "cd '$(pwd)' && source .venv/bin/activate && export PAOP_API_KEY=dev-key-DO-NOT-USE-IN-PRODUCTION && python src/external_interface/main.py"' &
        log_message "INFO" "Started API server in a new terminal window"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        if command -v gnome-terminal &> /dev/null; then
            gnome-terminal -- bash -c "cd $(pwd) && source .venv/bin/activate && export PAOP_API_KEY=dev-key-DO-NOT-USE-IN-PRODUCTION && python src/external_interface/main.py; exec bash" &
            log_message "INFO" "Started API server in a new terminal window"
        else
            log_message "WARN" "Could not start API server in a new terminal window"
            log_message "INFO" "You can manually start the API server with: python src/external_interface/main.py"
        fi
    else
        log_message "WARN" "Unsupported OS for opening new terminal window"
        log_message "INFO" "You can manually start the API server with: python src/external_interface/main.py"
    fi
    
    # Wait a moment for the API to start
    sleep 2
    
    # Run the agent supervisor
    log_message "INFO" "Starting agent supervisor..."
    python src/supervisor.py --config config/supervisor.yml >> $LOG_FILE 2>&1 &
    SUPERVISOR_PID=$!
    log_message "INFO" "Agent supervisor started (PID: $SUPERVISOR_PID)"
    
    log_message "INFO" "PAOP system is now running locally"
    log_message "INFO" "API server accessible at: http://localhost:8000"
    log_message "INFO" "To stop the system, press Ctrl+C"
    
    # Set up trap to handle clean shutdown
    trap shutdown_local_system INT
    
    # Wait for user to press Ctrl+C
    wait $SUPERVISOR_PID
}

# Function to shut down the local system
shutdown_local_system() {
    log_message "INFO" "Shutting down PAOP system..."
    
    # Kill the supervisor process
    if [ -n "$SUPERVISOR_PID" ]; then
        kill -15 $SUPERVISOR_PID 2>/dev/null || true
    fi
    
    # Find and kill the API process (by name)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        pkill -f "python src/external_interface/main.py" 2>/dev/null || true
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        pkill -f "python src/external_interface/main.py" 2>/dev/null || true
    fi
    
    log_message "INFO" "PAOP system shut down"
    exit 0
}

# Function to build and run Docker container
run_docker_system() {
    log_message "INFO" "Running PAOP system in Docker..."
    
    # Check if Docker is available
    if [ "$DOCKER_AVAILABLE" != true ]; then
        log_message "ERROR" "Docker is required for container deployment but not installed"
        exit 1
    fi
    
    # Build Docker image
    log_message "INFO" "Building Docker image..."
    docker build -t paop:dev . >> $LOG_FILE 2>&1
    
    # Run Docker container
    log_message "INFO" "Running Docker container..."
    docker run --name paop-container -p 8000:8000 -d paop:dev
    
    # Check if container is running
    if docker ps | grep paop-container > /dev/null; then
        log_message "INFO" "Docker container is running"
        log_message "INFO" "API server accessible at: http://localhost:8000"
    else
        log_message "ERROR" "Failed to start Docker container"
        docker logs paop-container >> $LOG_FILE 2>&1
        exit 1
    fi
    
    log_message "INFO" "To stop the container, run: docker stop paop-container"
    log_message "INFO" "To view logs, run: docker logs paop-container"
}

# Function to present menu and get user choice
show_menu() {
    echo -e "${BOLD}==================================================${NC}"
    echo -e "${BOLD}                    Run Options                    ${NC}"
    echo -e "${BOLD}==================================================${NC}"
    echo "1. Run locally (Python virtual environment)"
    echo "2. Run in Docker container"
    echo "3. Run both local and Docker systems"
    echo "4. Exit"
    echo
    
    read -p "Enter your choice (1-4): " choice
    
    case $choice in
        1)
            DEPLOYMENT_MODE="local"
            ;;
        2)
            DEPLOYMENT_MODE="docker"
            ;;
        3)
            DEPLOYMENT_MODE="both"
            ;;
        4)
            log_message "INFO" "Exiting..."
            exit 0
            ;;
        *)
            log_message "ERROR" "Invalid choice"
            show_menu
            ;;
    esac
}

# Main execution flow
main() {
    # Check prerequisites
    check_prerequisites
    
    # Set up environment
    setup_environment
    
    # Run tests
    run_tests
    
    # Show menu and get deployment mode
    show_menu
    
    # Deploy based on chosen mode
    case $DEPLOYMENT_MODE in
        "local")
            run_local_system
            ;;
        "docker")
            run_docker_system
            ;;
        "both")
            run_docker_system
            echo
            log_message "INFO" "Docker system started, now starting local system..."
            echo
            run_local_system
            ;;
    esac
}

# Run the main function
main

# Deactivate virtual environment when done
deactivate || true